# Generated by Django 3.1.3 on 2021-08-08 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('repeat_type', models.CharField(choices=[('repetition', 'Repetition'), ('frequency', 'Frequency')], max_length=100)),
                ('weekdays', models.CharField(choices=[('sun', 'SUN'), ('mon', 'MON'), ('tue', 'TUE'), ('wed', 'WED'), ('thu', 'THU'), ('fri', 'FRI'), ('sat', 'SAT')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
